version: '2.3'
services:
  cdeep3m:
    image: cdeep3m
    build:
      dockerfile: Dockerfile
      context: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: /train/augdata /train/trainout # runtraining.sh COMMAND 
    volumes:
      - ./train:/train